### ISSUE TITLE
TODO incorrectly detected in jupyter notebook

### ISSUE THREAD

**Issue by SamVanhoutte** [judepereira/checktodo#7]
Hello, 

We are using your todo addin and love it for all of our Arcus projects on github.
However, we started a Python library there and that github repo contains some jupyter notebooks.  And for one reason I cannot understand, it's blocking our PR's because a TODO seems to be detected in the ipynb files, where I don't see it.

```
Added/edited TODO items found:

samples/images_operations.ipynb#L73: "image/png": "iVBORw0KGgoAAAANSUhEUgAABIQAAAHWCAYAAAAGrFJtAAAABHNCSVQICAg
```
Screenshot:
![image](https://user-images.githubusercontent.com/3539605/81912642-2503db00-95cf-11ea-9827-835f0a90f39c.png)

Feel free to check the actual [PR](https://github.com/arcus-azure/arcus.ml/pull/43/checks?check_run_id=673767357) if you need more info.

**Comment by judepereira** [comment]
hey @SamVanhoutte, thanks for the details! A fix for this went a while ago, but it seems like it wasn't deployed to production. Let me check it out, and will get back to you.

**Comment by SamVanhoutte** [comment]
Thanks - appreciate the fast response.

**Comment by judepereira** [comment]
hey @SamVanhoutte, I just deployed CheckTODO, and it seems to be handling it correctly now. I created this PR here to test https://github.com/judepereira/arcus.ml/pull/1.

Could you please test this out in your own repo as well? If it works well, we can close this issue then.

Thanks!

**Comment by SamVanhoutte** [comment]
I think it's okay, as I've checked the PR where it was incorrectly flagged as TODO and now it's stated as OK / Green
